////Requests de servicios

### Buscar todos los servicios

GET http://localhost:1234/services


### Buscar un servicio por id

GET http://localhost:1234/services/1


### Crear un servicio

POST http://localhost:1234/services
Content-Type: application/json

{
  "description":"Fumigación",
  "hourValue":60500
}


### Actualizar un servicio

PATCH http://localhost:1234/services/1
Content-Type: application/json

{
  "hourValue":70000
}


### Borrar un servicio

DELETE http://localhost:1234/services/2



//// Requests de Usuarios

### obtener todos los usuarios
GET http://localhost:1234/users

### obtener un usuario por id
GET http://localhost:1234/users/1

### borrar un usuario
DELETE http://localhost:1234/users/1

### agregar un usuario
POST http://localhost:1234/users
Content-Type: application/json

{
    "nombre_usuario": "francisco00",
    "clave": "12345",
    "email": "francisco@gmail",
    "telefono": "123456",
    "nombre": "Franciscoooooo",
    "apellido": "Figueroa Casas",
    "direccion": "Newbery 9063",
    "tipo_usuario": 2
  }

### actualizar un usuario
PATCH http://localhost:1234/users/1
Content-Type: application/json

{
    "direccion": "aaaaaaaaaaaaaaaaaaaaaaaaaaa"
  }

