### obtener todos los usuarios
GET http://localhost:3000/users

### obtener un usuario por id
GET http://localhost:3000/users/1

### borrar un usuario
DELETE http://localhost:3000/users/2

### agregar un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
    "id_usuario": 5,
    "nombre_usuario": "francisco",
    "clave": "12345",
    "email": "francisco@gmail",
    "telefono": "123456",
    "nombre": "Franciscoooooo",
    "apellido": "Figueroa Casas",
    "direccion": "Newbery 9063",
    "tipo_usuario": 2
  }

### actualizar un usuario
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "direccion": "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
  }