////Requests de servicios

### Buscar todos los servicios

GET http://localhost:1234/services


### Buscar un servicio por id

GET http://localhost:1234/services/5


### Crear un servicio

POST http://localhost:1234/services
Content-Type: application/json

{
  "description":"bdb",
  "hourValue":123
}


### Actualizar un servicio

PATCH http://localhost:1234/services/6
Content-Type: application/json

{
  "hourValue":70000
}


### Borrar un servicio

DELETE http://localhost:1234/services/2

//// Requests de Servicios-Clientes


### Buscar todos los servicios de los clientes

GET http://localhost:1234/services-clients


### Buscar un servicio de un cliente por id

GET http://localhost:1234/services-clients/3/2/2023-10-05



### Crear un nuevo servicio de un cliente

POST http://localhost:1234/services-clients
Content-Type: application/json

{
  "idServ": 3,
  "idCli":2,
  "date":"2023-10-08T15:30:00.000Z",
  "hourAmmount":3
}


### Borrar un servicio de un cliente por id

DELETE http://localhost:1234/services-clients/3/2/2023-10-08



### Actualizar un servicio

PATCH http://localhost:1234/services-clients/3/2/2023-10-08
Content-Type: application/json

{
  "hourAmmount":5
}




//// Requests de Usuarios

### obtener todos los usuarios
GET http://localhost:3000/users

### obtener un usuario por id
GET http://localhost:3000/users/1

### borrar un usuario
DELETE http://localhost:3000/users/2

### agregar un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
    "id_usuario": 5,
    "nombre_usuario": "francisco",
    "clave": "12345",
    "email": "francisco@gmail",
    "telefono": "123456",
    "nombre": "Franciscoooooo",
    "apellido": "Figueroa Casas",
    "direccion": "Newbery 9063",
    "tipo_usuario": 2
  }

### actualizar un usuario
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "direccion": "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
  }

